import { World } from '../world/World.js';import { Simulation } from '../simulation/Simulation.js';import { Machine } from '../entities/Machine.js';import { BuildSystem } from '../building/BuildSystem.js';import { Camera } from '../rendering/Camera.js';import { Renderer } from '../rendering/Renderer.js';import { InputManager } from '../input/InputManager.js';import { MouseController } from '../input/MouseController.js';import { UIManager } from '../ui/UIManager.js';import { GameLoop } from './GameLoop.js';import { MAP_WIDTH, MAP_HEIGHT } from '../utils/Constants.js';
export class Game {
  constructor(canvas){this.canvas=canvas;this.world=new World(MAP_WIDTH,MAP_HEIGHT);this.setupMap();this.sim=new Simulation(this.world);this.build=new BuildSystem(this.world,this.sim);this.camera=new Camera();this.renderer=new Renderer(canvas,this.camera);this.renderer.buildSystem=this.build;this.input=new InputManager(canvas);this.mouse=new MouseController(canvas,this.camera,this.renderer.tile);this.hover={x:0,y:0};this.setupInput();this.sim.initialize();this.ui=new UIManager(this);this.setSpeed(1);this.centerCamera();this.loop=new GameLoop(dt=>this.update(dt),()=>this.render());}
  setupMap(){const w=this.world;const left=8,right=55,top=10,bottom=46;for(let x=left;x<=right;x++){w.setMaterial(x,top,'concrete');w.setMaterial(x,bottom,'concrete');}for(let y=top;y<=bottom;y++){w.setMaterial(left,y,'concrete');w.setMaterial(right,y,'concrete');}w.setMaterial(left,40,'air');w.setMaterial(right,18,'air');w.addEntity(new Machine(20,18,{name:'Máquina 1',heatOutput:8000}));w.addEntity(new Machine(32,18,{name:'Máquina 2',heatOutput:12000}));w.addEntity(new Machine(44,18,{name:'Máquina 3',heatOutput:15000}));}
  setupInput(){this.mouse.onMove=grid=>{this.hover=grid;this.renderer.hover=grid;};this.mouse.onPrimary=grid=>{if(!this.world.inBounds(grid.x,grid.y))return;if(this.build.selected){const r=this.build.place(grid.x,grid.y);if(!r.ok)this.toast(r.reason);}else this.ui?.inspectAt(grid.x,grid.y);};this.mouse.onSecondary=()=>this.build.select(null);addEventListener('keydown',e=>{if(e.repeat)return;if(e.code==='Space'){e.preventDefault();this.sim.togglePause();}if(e.code==='KeyR')this.build.rotate();if(e.code==='F3'){e.preventDefault();this.renderer.debug=!this.renderer.debug;}if(e.code==='Escape')this.build.select(null);if(['Digit1','Digit2','Digit4'].includes(e.code))this.setSpeed(Number(e.code.at(-1)));});}
  centerCamera(){const r=this.canvas.getBoundingClientRect(),worldW=this.world.width*this.renderer.tile,worldH=this.world.height*this.renderer.tile;this.camera.x=(worldW-r.width)/2;this.camera.y=(worldH-r.height)/2;}
  setSpeed(v){this.sim.setSpeed(v);this.ui?.setSpeedButtons(v);}
  update(dt){const speed=360*dt; if(this.input.down('KeyW'))this.camera.move(0,-speed);if(this.input.down('KeyS'))this.camera.move(0,speed);if(this.input.down('KeyA'))this.camera.move(-speed,0);if(this.input.down('KeyD'))this.camera.move(speed,0);this.sim.update(dt);this.ui?.update();}
  render(){this.renderer.draw(this.world,this.sim);}
  toast(text){const t=document.querySelector('#toast');if(!t)return;t.textContent=text;t.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.remove('show'),1200);}
  start(){this.loop.start();}
}
