const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export class LandExpansionPanel{
  constructor({root,manager,onModeChange=()=>{},onMessage=()=>{}}){this.root=root;this.manager=manager;this.onModeChange=onModeChange;this.onMessage=onMessage;this.mode=false;this.selected=null;
    root?.addEventListener('click',event=>{const toggle=event.target.closest('[data-land-close]');if(toggle){this.setMode(false);return;}const item=event.target.closest('[data-land-id]');if(item){this.select(item.dataset.landId);return;}if(event.target.closest('[data-land-buy]'))this.buy();});
  }
  setMode(value){this.mode=Boolean(value);if(!this.mode)this.selected=null;if(this.root)this.root.hidden=!this.mode;this.onModeChange(this.mode);this.update();}
  toggle(){this.setMode(!this.mode);}
  select(id){const area=this.manager.land?.areas.get(id);if(!area)return false;this.selected=id;this.update();return true;}
  selectAt(x,y){const area=this.manager.land?.areaAt(x,y);return area?this.select(area.id):false;}
  buy(){if(!this.selected)return;const result=this.manager.purchaseLandExpansion(this.selected);if(!result.ok){this.onMessage(result.reason==='INSUFFICIENT_FUNDS'?'Dinheiro insuficiente para comprar este terreno.':result.reason==='AREA_NOT_ADJACENT'?'A área precisa tocar uma propriedade adquirida.':'Área indisponível.');return;}this.onMessage(result.area.name+' adquirida · '+result.statistics.ownedTiles.toLocaleString('pt-BR')+' tiles próprios.');this.selected=null;this.update();}
  update(){if(!this.root)return;const land=this.manager.land;if(!this.mode||!land){this.root.hidden=true;return;}const stats=land.statistics({placedMaterials:[...this.manager.build?.placedMaterials?.keys?.()||[]].map(index=>({x:index%land.world.width,y:Math.floor(index/land.world.width)})),investment:this.manager.state.landInvestmentTotal});
    const selected=this.selected?land.areas.get(this.selected):null,quote=selected?this.manager.quoteLandExpansion(selected.id):null;
    const rows=[...land.areas.values()].map(area=>{const owned=land.isAreaOwned(area.id),available=land.availableExpansions().find(item=>item.id===area.id)?.available;return `<button class="land-area ${owned?'owned':available?'available':'locked'} ${this.selected===area.id?'selected':''}" data-land-id="${esc(area.id)}"><span>${owned?'✓':available?'＋':'🔒'} ${esc(area.name)}</span><small>${area.width} × ${area.height} · ${(area.width*area.height).toLocaleString('pt-BR')} tiles ${owned?'· adquirido':'· '+('R$ '+area.cost.toLocaleString('pt-BR'))}</small></button>`;}).join('');
    this.root.innerHTML=`<section class="land-dialog" role="dialog" aria-modal="true" aria-labelledby="landTitle"><header><div><small>PROPRIEDADE DO CPD</small><h2 id="landTitle">Expandir terreno</h2></div><button data-land-close aria-label="Fechar">×</button></header><div class="land-stats"><span>Adquirido <b>${stats.ownedTiles.toLocaleString('pt-BR')}</b></span><span>Ocupado <b>${stats.occupiedTiles.toLocaleString('pt-BR')}</b></span><span>Livre <b>${stats.freeTiles.toLocaleString('pt-BR')}</b></span><span>Densidade de racks <b>${stats.rackDensity.toFixed(1)}%</b></span><span>Investimento <b>R$ ${stats.investment.toLocaleString('pt-BR')}</b></span></div><p>Clique numa área no mapa ou escolha uma expansão. Áreas bloqueadas não aceitam construções.</p><div class="land-area-list">${rows}</div>${selected?`<footer><span>${esc(selected.name)} · ${selected.width} × ${selected.height}<br><b>Custo R$ ${(selected.cost||0).toLocaleString('pt-BR')}</b> · saldo após compra R$ ${Math.max(0,quote?.cashAfter||0).toLocaleString('pt-BR')}</span><button data-land-buy ${!quote?.ok||this.manager.cash<selected.cost?'disabled':''}>Comprar área</button></footer>`:''}</section>`;
  }
}
