import { Toolbar } from './Toolbar.js';import { Inspector } from './Inspector.js';import { MetricsPanel } from './MetricsPanel.js';
export class UIManager {
  constructor(game){this.game=game;this.toolbar=new Toolbar(document.querySelector('#tools'),game.build);this.inspector=new Inspector(document.querySelector('#inspector'));this.metrics=new MetricsPanel(document.querySelector('#metrics'));this.graph=document.querySelector('#history');this.graphCtx=this.graph.getContext('2d');this.bind();game.build.onChange=()=>this.toolbar.render();}
  bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{this.game.renderer.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});document.querySelector('#pauseBtn').onclick=()=>this.game.sim.togglePause();document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>this.game.setSpeed(Number(b.dataset.speed)));document.querySelector('#resetBtn').onclick=()=>location.reload();}
  inspectAt(x,y){const e=this.game.world.entityAt(x,y);this.inspector.setTarget(e?{kind:'entity',entity:e}:{kind:'tile',x,y});}
  update(){const g=this.game,s=g.sim;this.metrics.update(s,g.build);this.inspector.update(g.world);document.querySelector('#clock').textContent=this.formatTime(s.elapsed);document.querySelector('#missionText').textContent=s.mission.message;document.querySelector('#pauseBtn').textContent=s.paused?'▶ Continuar':'Ⅱ Pausar';document.querySelector('#speedLabel').textContent=`${s.speed}×`;document.querySelector('#rotateHint').textContent=g.build.selected&&['fan','exhaust'].includes(g.build.selected)?`Direção: ${['→','↓','←','↑'][g.build.rotation]} · R gira`:'';this.drawGraph();this.updateEndState();}
  setSpeedButtons(v){document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===v));}
  formatTime(s){const m=Math.floor(s/60),sec=Math.floor(s%60);return `${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`;}
  drawGraph(){const c=this.graph,ctx=this.graphCtx,r=c.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(10,Math.floor(r.width*dpr)),h=Math.max(10,Math.floor(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h;}ctx.setTransform(dpr,0,0,dpr,0,0);const W=w/dpr,H=h/dpr;ctx.clearRect(0,0,W,H);ctx.strokeStyle='rgba(148,163,184,.15)';ctx.lineWidth=1;for(let i=1;i<4;i++){ctx.beginPath();ctx.moveTo(0,H*i/4);ctx.lineTo(W,H*i/4);ctx.stroke();}const data=this.game.sim.history;if(data.length<2)return;const min=20,max=Math.max(85,...data.map(d=>d.max));const draw=(key,stroke)=>{ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.beginPath();data.forEach((d,i)=>{const x=i/(data.length-1)*W,y=H-(d[key]-min)/(max-min)*H;i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();};draw('max','#fb7185');draw('avg','#67e8f9');}
  updateEndState(){const s=this.game.sim;if(s.mission.state==='running')return;const modal=document.querySelector('#endModal');modal.classList.add('show');document.querySelector('#endTitle').textContent=s.mission.state==='won'?'MISSÃO CONCLUÍDA':'FALHA TÉRMICA';document.querySelector('#endText').textContent=s.mission.state==='won'?'Você manteve todas as máquinas abaixo de 40°C dentro do limite elétrico.':s.mission.failReason;}
}
