import { level06Map } from '../maps/level06Map.js';

export const level06={
  id:'critical-facility',number:6,name:'Data Center Crítico',difficulty:6,
  tagline:'Contenção de corredores frios e quentes',
  description:'Um data center de missão crítica precisa manter as frentes dos racks frias e conter o ar de exaustão nos corredores quentes centrais.',
  briefing:'Organize o resfriamento das duas salas de servidores: insufle ar frio pelos corredores externos e recolha o ar quente nos corredores centrais, onde as traseiras dos racks se encontram. Preserve também a infraestrutura elétrica e de processo durante picos de carga e uma onda de calor.',
  thermalSystems:{simpleCooling:true,waterCooling:true,coolingUnitModel:'commercial'},
  map:level06Map,environment:{outdoorTemperature:25},budget:65000,powerLimit:20000,missionDuration:600,
  inventory:{pipe:200,pump:4,tank:3,radiator:6,exchanger:8,wall:70,insulation:80,copper:30,fan:12,exhaust:6,sensor:16,coolingUnit:4,duct:400,supplyVent:8,demolish:Infinity},
  zones:[
    {id:'server-a-cold-north',name:'Cold Aisle A · Norte',x:7,y:8,width:22,height:4,target:36,visualStyle:'server'},
    {id:'server-a-hot',name:'Hot Aisle A · Central',x:7,y:13,width:22,height:5,target:48,visualStyle:'industrial'},
    {id:'server-a-cold-south',name:'Cold Aisle A · Sul',x:7,y:19,width:22,height:4,target:36,visualStyle:'server'},
    {id:'server-b-cold-north',name:'Cold Aisle B · Norte',x:35,y:8,width:22,height:4,target:36,visualStyle:'server'},
    {id:'server-b-hot',name:'Hot Aisle B · Central',x:35,y:13,width:22,height:5,target:48,visualStyle:'industrial'},
    {id:'server-b-cold-south',name:'Cold Aisle B · Sul',x:35,y:19,width:22,height:4,target:36,visualStyle:'server'},
    {id:'electrical',name:'Sala Elétrica',x:64,y:8,width:22,height:15,target:45,visualStyle:'utility'},
    {id:'pump-room',name:'Sala de Bombas',x:8,y:32,width:20,height:10,target:45,visualStyle:'utility'},
    {id:'process-a-zone',name:'Processo A',x:35,y:32,width:20,height:10,target:50,visualStyle:'industrial'},
    {id:'process-b-zone',name:'Processo B',x:63,y:32,width:23,height:10,target:50,visualStyle:'industrial'},
    {id:'control-room',name:'Sala de Controle',x:8,y:49,width:20,height:7,target:32,visualStyle:'office'},
    {id:'technical-corridor',name:'Corredor Técnico',x:3,y:24,width:90,height:8,target:45,visualStyle:'corridor'},
  ],
  entities:[
    ...[
      {id:'a1',x:10,y:12,load:2400,intake:{x:0,y:-1}},
      {id:'a2',x:18,y:12,load:2500,intake:{x:0,y:-1}},
      {id:'a3',x:26,y:12,load:2600,intake:{x:0,y:-1}},
      {id:'a4',x:10,y:18,load:2400,intake:{x:0,y:1}},
      {id:'a5',x:18,y:18,load:2500,intake:{x:0,y:1}},
      {id:'a6',x:26,y:18,load:2600,intake:{x:0,y:1}},
      {id:'b1',x:38,y:12,load:2500,intake:{x:0,y:-1}},
      {id:'b2',x:46,y:12,load:2650,intake:{x:0,y:-1}},
      {id:'b3',x:54,y:12,load:2850,intake:{x:0,y:-1}},
      {id:'b4',x:38,y:18,load:2500,intake:{x:0,y:1}},
      {id:'b5',x:46,y:18,load:2650,intake:{x:0,y:1}},
      {id:'b6',x:54,y:18,load:2850,intake:{x:0,y:1}},
    ].map(({id,x,y,load,intake})=>({
      type:'serverRack',id:`srv-${id}`,name:`Rack ${id.toUpperCase()}`,x,y,heatOutput:load,
      zoneId:id.startsWith('a')?'server-a':'server-b',category:'serverRack',
      airIntakeDirection:intake,airExhaustDirection:{x:-intake.x,y:-intake.y},
    })),
    {type:'machine',id:'transformer-a',name:'Transformador A',x:72,y:15,heatOutput:14000,zoneId:'electrical',category:'electrical',failureTemperature:90},
    {type:'machine',id:'process-a-main',name:'Processo A',x:44,y:36,heatOutput:18000,zoneId:'process-a-zone',category:'process',failureTemperature:85},
    {type:'machine',id:'process-b-main',name:'Processo B',x:72,y:36,heatOutput:22000,zoneId:'process-b-zone',category:'process',failureTemperature:85,enabled:false,startAt:99999},
    {type:'passiveHeat',id:'control-load',name:'Estações de controle',x:18,y:52,heatOutput:1500,zoneId:'control-room',category:'computer'},
    {type:'exhaust',id:'legacy-exhaust-a',x:89,y:28,direction:{x:1,y:0},locked:true},
    {type:'exhaust',id:'legacy-exhaust-b',x:89,y:31,direction:{x:1,y:0},locked:true},
  ],
  objectives:[
    {type:'zoneTemperature',zoneId:'server-a-cold-north',max:36,label:'Cold Aisle A norte < 36°C'},
    {type:'zoneTemperature',zoneId:'server-a-hot',max:48,label:'Hot Aisle A central < 48°C'},
    {type:'zoneTemperature',zoneId:'server-a-cold-south',max:36,label:'Cold Aisle A sul < 36°C'},
    {type:'zoneTemperature',zoneId:'server-b-cold-north',max:36,label:'Cold Aisle B norte < 36°C'},
    {type:'zoneTemperature',zoneId:'server-b-hot',max:48,label:'Hot Aisle B central < 48°C'},
    {type:'zoneTemperature',zoneId:'server-b-cold-south',max:36,label:'Cold Aisle B sul < 36°C'},
    {type:'zoneTemperature',zoneId:'electrical',max:45,label:'Sala elétrica < 45°C'},
    {type:'zoneTemperature',zoneId:'control-room',max:32,label:'Controle < 32°C'},
    {type:'coolingCapacityMargin',min:.15,label:'Reserva de refrigeração ≥ 15%'},
    {type:'activeCoolingUnits',min:2,label:'Mantenha 2 condensadoras operacionais'},
    {type:'machineTemperature',max:65,filter:{category:'process'},label:'Processos < 65°C'},
    {type:'powerBelow',max:20000,label:'Consumo de refrigeração < 20 kW'},
  ],
  failures:[
    {type:'entityLimits',hold:30},
    {type:'coolingUnitOverload',hold:60,message:'Uma condensadora permaneceu sobrecarregada. Adicione capacidade ou reduza a carga.'},
    {type:'zoneOverheat',zoneId:'control-room',temperature:40,hold:30,message:'A sala de controle tornou-se inoperável.'},
  ],
  events:[
    {time:180,type:'machineLoad',filter:{zoneId:'server-b'},multiplier:1.3,message:'EVENTO 1: os racks do data hall B entraram em pico de carga.'},
    {time:300,type:'activateMachine',filter:{missionId:'process-b-main'},message:'EVENTO 2: Processo B iniciou operação.'},
    {time:420,type:'outdoorTemperature',value:35,message:'EVENTO 3: onda de calor — exterior agora em 35°C.'},
  ],
  tips:['As frentes dos racks captam ar frio nos corredores externos; as traseiras expelem ar para o corredor quente central.','Use redes independentes para redundância e evitar uma falha única.','Dutos podem cruzar paredes sem abrir caminho para o ar da sala.','Escolha condensadoras internas ou externas e mantenha margem para os picos de carga e a onda de calor.'],
};

