export const datacenterSandbox={
  id:'datacenter-sandbox',number:0,name:'Data Center Sandbox',difficulty:0,campaign:false,datacenterSandbox:true,
  tagline:'Operação contínua · crescimento por contratos',
  description:'Construa um data center em terreno aberto, aceite clientes e equilibre caixa, energia e refrigeração.',
  briefing:'Comece com R$ 150 mil, 100 kW contratados e um terreno livre. Aceite contratos, planeje a infraestrutura e expanda sua propriedade.',
  thermalSystems:{simpleCooling:true,waterCooling:true,allBuildTools:true,coolingUnitModel:'compact'},
  map:{width:128,height:80,initialTemperature:25,rooms:[],lines:[],openings:[]},
  environment:{outdoorTemperature:25},budget:150000,powerLimit:100000,missionDuration:Infinity,objectiveStartAt:0,
  inventory:{wall:180,insulation:60,copper:20,fan:8,exhaust:4,sensor:12,coolingUnit:3,duct:200,supplyVent:16,
    serverRack:Infinity,demolish:Infinity},
  datacenter:{initialCash:150000,powerCapacityKW:100,energyTariff:.55,coolingMaintenanceDaily:110,allBuildTools:true,unlimitedBuildInventory:true,
    land:{initialArea:'core',areas:[
      {id:'core',name:'Terreno inicial',x:32,y:16,width:64,height:48,cost:0,owned:true},
      {id:'north',name:'Expansão Norte',x:0,y:0,width:128,height:16,cost:480000},
      {id:'west',name:'Expansão Oeste',x:0,y:16,width:32,height:48,cost:320000},
      {id:'east-1',name:'Expansão Leste 1',x:96,y:16,width:32,height:24,cost:60000},
      {id:'east-2',name:'Expansão Leste 2',x:96,y:40,width:32,height:24,cost:90000},
      {id:'south-west',name:'Expansão Sul Oeste',x:0,y:64,width:64,height:16,cost:140000},
      {id:'south-east',name:'Expansão Sul Leste',x:64,y:64,width:64,height:16,cost:210000},
    ]}},
  zones:[],entities:[],objectives:[],failures:[],events:[],startMessage:'Aceite um contrato no mercado e organize a infraestrutura no seu terreno.',
};
