export const BUILD_CATALOG = {
  wall:       { label:'Parede', icon:'▦', cost:35, inventory:50, kind:'material', material:'concrete', category:'Estrutura', description:'Concreto estrutural. Armazena calor e conduz lentamente.' },
  insulation: { label:'Isolante', icon:'▧', cost:25, inventory:20, kind:'material', material:'insulation', category:'Estrutura', description:'Barreira de baixa condutividade para reduzir transferência térmica.' },
  copper:     { label:'Cobre', icon:'▤', cost:80, inventory:10, kind:'material', material:'copper', category:'Estrutura', description:'Condutor térmico de alta eficiência para espalhar calor.' },
  fan:        { label:'Ventilador', icon:'✣', cost:100, inventory:4, kind:'entity', category:'Ar', power:'300 W', description:'Fan por curva pressão-vazão. Geometria, paredes e restrições determinam o fluxo real.' },
  exhaust:    { label:'Exaustor', icon:'◉', cost:300, inventory:2, kind:'entity', category:'Ar', power:'500 W', description:'Fan de maior pressão que remove calor conforme a vazão física realmente obtida.' },
  pipe:       { label:'Tubo', icon:'━', cost:10, inventory:40, kind:'entity', category:'Água', description:'Transporta água e energia no sentido definido pela bomba. Redes devem formar um loop sem ramificações.' },
  pump:       { label:'Bomba', icon:'⟳', cost:600, inventory:1, kind:'entity', category:'Água', power:'800 W', description:'Define o sentido da circulação. Pressione R para girar a saída; somente circuitos fechados geram vazão.' },
  tank:       { label:'Tanque', icon:'▰', cost:500, inventory:1, kind:'entity', category:'Água', description:'Reserva térmica de 120 kg de água. Amortece picos sem esconder a evolução da temperatura.' },
  radiator:   { label:'Radiador', icon:'▥', cost:700, inventory:2, kind:'entity', category:'Água', description:'Retira calor da água e aquece uma área 3×3 do ar. Ventilação aumenta a potência de rejeição.' },
  exchanger:  { label:'Trocador', icon:'HX', cost:450, inventory:3, kind:'entity', category:'Água', description:'Transfere calor da máquina adjacente para a água somente quando existe circulação.' },
  sensor:     { label:'Sensor', icon:'°', cost:75, inventory:5, kind:'entity', category:'Controle', description:'Mede temperatura atual, média e máxima do tile.' },
  airHandler: { label:'Air Handler', icon:'AH', cost:8000, inventory:1, kind:'entity', category:'HVAC', description:'Até 2,5 m³/s e 25 kW de resfriamento; insuflação alvo de 14°C. Requer dutos e condensadora próxima.' },
  condenser:  { label:'Condensadora', icon:'CD', cost:10000, inventory:1, kind:'entity', category:'HVAC', description:'Capacidade nominal de rejeição de 30 kW. Instale fora das zonas para evitar recirculação de calor.' },
  smallDuct:  { label:'Duto pequeno', icon:'═', cost:80, inventory:40, kind:'utility', category:'HVAC', description:'Duto de seção 0,08 m²; baixo custo e maior perda de carga.' },
  mediumDuct: { label:'Duto médio', icon:'═', cost:140, inventory:60, kind:'utility', category:'HVAC', description:'Duto de seção 0,18 m² para redes de capacidade intermediária.' },
  largeDuct:  { label:'Duto grande', icon:'═', cost:230, inventory:30, kind:'utility', category:'HVAC', description:'Duto de seção 0,35 m² e menor perda de carga.' },
  supplyVent: { label:'Vent insuflação', icon:'↓', cost:180, inventory:4, kind:'entity', category:'HVAC', description:'Entrega ar resfriado; R orienta o jato para a área atendida.' },
  returnVent: { label:'Vent retorno', icon:'↑', cost:160, inventory:4, kind:'entity', category:'HVAC', description:'Retira ar do ambiente; dutos ligados a este vent são identificados como retorno.' },
  damper:     { label:'Damper', icon:'╫', cost:120, inventory:10, kind:'utility', category:'HVAC', description:'Equilibra ramais; selecione-o e use U/J para ajustar a abertura.' },
  demolish:   { label:'Remover', icon:'⌫', cost:0, inventory:Infinity, kind:'tool', category:'Ferramenta', description:'Remove equipamentos e materiais construídos.' },
};
