import {contractRequirements,escapeContractHtml as esc,formatContractDaily as daily,formatContractKw as kw,formatContractMoney as money} from '../ContractCenterDataService.js';

function detail(contract,manager,service,ui){
  const equipment=service.resolveEquipment(contract),requirements=contractRequirements(contract),availability=contract.activeSeconds?100*(contract.uptimeSeconds||0)/contract.activeSeconds:null;
  const status=service.contractState(contract),rows=[];
  if(contract.modality==='compute'){
    const request=contract.computeRequirements||{},allocation=contract.allocations||[];
    rows.push(['Recursos contratados',requirements],['CPU reservada',`${Number(request.vcpu)||0} vCPU`],['RAM reservada',`${Number(request.ramGB)||0} GB`],['GPUs contratadas',`${Number(request.gpuCount)||0} · VRAM mínima ${Number(request.gpuMinVramGB)||0} GB`],['Storage reservado',`${Number(request.storageTB)||0} TB`],['Alocações ativas',`${allocation.length} blocos em ${equipment.length} rack(s)`]);
    for(const rack of equipment){const parts=allocation.filter(item=>item.assetId===rack.assetId).map(item=>[item.vcpu&&`${item.vcpu} vCPU`,item.ramGB&&`${item.ramGB} GB RAM`,item.gpuDevices?.length&&`${item.gpuDevices.length} GPU`,item.storageTB&&`${item.storageTB} TB`].filter(Boolean).join(' · '));rows.push([rack.name||rack.assetId,`${parts.join(', ')} · posição ${rack.x+1}, ${rack.y+1}`]);}
  }else{
    const racks=manager.world.entitiesByType('serverRack').filter(rack=>rack.contractId===contract.id);
    rows.push(['Racks contratados',`${Number(contract.rackCount)||0}`],['Racks instalados',`${racks.length} / ${Number(contract.rackCount)||0}`],['Potência por rack',kw(contract.powerPerRackKW)],['Capacidade comprometida',kw((contract.rackCount||0)*(contract.powerPerRackKW||0))],['Racks vinculados',racks.map(rack=>`${rack.name||'Rack'} · ${rack.x+1},${rack.y+1}`).join(' · ')||'Ainda não instalados']);
  }
  rows.push(['Mensalidade',`${money(contract.monthlyFee)}/mês · ${daily(contract.monthlyFee)}/dia`],['Assinatura',`Dia ${contract.acceptedDay??'—'}`],['Dias restantes',`${Math.max(0,(contract.expiresDay||manager.clock.day)-manager.clock.day)}`],['SLA térmico',`${Number(contract.maxInletTemperature)||0} °C máx.`],['Disponibilidade observada',availability==null?'Ainda sem amostra':`${availability.toFixed(2)}% / ${Number(contract.availability)||0}%`]);
  if(contract.computeDiagnostics?.length)rows.push(['Diagnóstico',contract.computeDiagnostics.join(' · ')]);
  if(contract.modality!=='compute'){
    for(const rack of manager.world.entitiesByType('serverRack').filter(item=>item.contractId===contract.id))rows.push([rack.name||'Rack',`Inlet ${(rack.inletTemperature||0).toFixed(1)} °C · ${kw((rack.heatGenerationPower||0)/1000)} de calor · ${rack.status||'NORMAL'}`]);
  }
  const canCancel=['active','installing'].includes(contract.status),pending=ui.cancelConfirm===contract.id;
  return `<aside class="cc-contract-details"><header><div><span class="cc-eyebrow">DETALHES DO SERVIÇO</span><h3>${esc(contract.clientName)}</h3></div><span class="cc-state ${status.key}">${esc(status.label)}</span></header><p>${esc(contract.productName||contract.tier||'Contrato')} · ${contract.modality==='compute'?'Cloud Services':'Colocation'} · ${esc(requirements)}</p><dl>${rows.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><div class="cc-detail-actions"><button type="button" data-contract-locate="${esc(contract.id)}" ${equipment.length?'':'disabled'}>⌖ Localizar no mapa (${equipment.length})</button>${canCancel?`<button class="danger" type="button" data-contract-cancel="${esc(contract.id)}">Cancelar contrato</button>`:''}</div>${pending?`<div class="cc-confirm" role="group" aria-label="Confirmar cancelamento"><b>Confirmar cancelamento de ${esc(contract.clientName)}?</b><p>O contrato será encerrado e as reservas Cloud serão liberadas. Equipamentos físicos próprios permanecerão no mapa. Consequências comerciais seguem as regras atuais de reputação e faturamento.</p><button type="button" data-cancel-abort>Voltar</button><button type="button" class="danger" data-cancel-confirm="${esc(contract.id)}">Confirmar cancelamento</button></div>`:''}</aside>`;
}

export function renderActiveContractsTab(manager,service,ui){
  const live=manager.state.contracts.filter(contract=>['active','installing'].includes(contract.status));
  const filtered=live.filter(contract=>ui.activeFilter==='all'||service.contractState(contract).key===ui.activeFilter);
  const rows=filtered.map(contract=>{const state=service.contractState(contract),availability=contract.activeSeconds?100*(contract.uptimeSeconds||0)/contract.activeSeconds:null;return `<button type="button" class="cc-contract-row ${ui.selectedContract===contract.id?'selected':''}" data-contract-select="${esc(contract.id)}"><span><b>${esc(contract.clientName)}</b><small>${esc(contract.productName||contract.tier||'Contrato')} · ${contract.modality==='compute'?'Cloud':'Colocation'}</small></span><span>${daily(contract.monthlyFee)}/dia</span><span>${contract.acceptedDay==null?'—':`D${contract.acceptedDay}`}</span><span>${Math.max(0,(contract.expiresDay||manager.clock.day)-manager.clock.day)} d</span><span>${availability==null?'—':availability.toFixed(2)+'%'}</span><i class="cc-state ${state.key}">${esc(state.label)}</i></button>`;}).join('');
  const selected=filtered.find(contract=>contract.id===ui.selectedContract)||filtered[0]||null;
  if(selected&&ui.selectedContract!==selected.id)ui.selectedContract=selected.id;
  return `<section class="cc-tab cc-active"><div class="cc-tab-heading"><div><span class="cc-eyebrow">CARTEIRA</span><h2>Em andamento</h2></div><b>${live.length} contratos</b></div><label class="cc-single-filter">Estado<select data-active-filter><option value="all" ${ui.activeFilter==='all'?'selected':''}>Todos</option><option value="installing" ${ui.activeFilter==='installing'?'selected':''}>Em instalação</option><option value="active" ${ui.activeFilter==='active'?'selected':''}>Ativo</option><option value="attention" ${ui.activeFilter==='attention'?'selected':''}>Atenção</option><option value="violated" ${ui.activeFilter==='violated'?'selected':''}>SLA violado / sem provisionamento</option></select></label>${live.length?`<div class="cc-active-layout"><div class="cc-contract-table"><div class="cc-contract-table-head"><span>Cliente / produto</span><span>Pagamento</span><span>Assinado</span><span>Restante</span><span>Disponibilidade</span><span>Estado</span></div>${rows||'<p class="cc-empty">Nenhum contrato neste estado.</p>'}</div>${selected?detail(selected,manager,service,ui):''}</div>`:'<p class="cc-empty">Não há contratos em instalação ou operação.</p>'}</section>`;
}
