import {contractRequirements,escapeContractHtml as esc,formatContractDaily as daily,formatContractMoney as money} from '../ContractCenterDataService.js';

export function renderHistoryTab(manager,ui){
  const ended=manager.state.contracts.filter(contract=>['completed','cancelled'].includes(contract.status));
  const items=ended.filter(contract=>{
    if(ui.historyState!=='all'&&contract.status!==ui.historyState)return false;
    if(ui.historyType==='cloud'&&contract.modality!=='compute')return false;
    if(ui.historyType==='colocation'&&contract.modality==='compute')return false;
    return !ui.historySearch||String(contract.clientName||'').toLocaleLowerCase('pt-BR').includes(ui.historySearch.toLocaleLowerCase('pt-BR'));
  }).sort((a,b)=>(b.commercialEndedDay||b.completedDay||b.cancelledDay||0)-(a.commercialEndedDay||a.completedDay||a.cancelledDay||0));
  const rows=items.map(contract=>{
    const actual=contract.activeSeconds?100*(contract.uptimeSeconds||0)/contract.activeSeconds:null;
    const realized=contract.lastBilledDay==null&&manager.state.commercialHistoryPartial?null:Number(contract.totalRecurringRevenue)||0;
    const equipment=contract.commercialResourceSnapshot||{},endReason=contract.commercialEndReason||contract.cancelReason||(contract.status==='completed'?'Prazo contratual concluído':'Cancelado');
    return `<article class="cc-history-card"><header><div><span class="cc-eyebrow">${contract.status==='completed'?'CONCLUÍDO':'CANCELADO'} · ${contract.modality==='compute'?'CLOUD':'COLOCATION'}</span><h3>${esc(contract.clientName)}</h3></div><b>${esc(contract.productName||contract.tier||'Contrato')}</b></header><p>${esc(contractRequirements({...contract,...equipment}))}</p><dl><div><dt>Assinado</dt><dd>${contract.acceptedDay==null?'Indisponível':`Dia ${contract.acceptedDay}`}</dd></div><div><dt>Encerrado</dt><dd>${contract.commercialEndedDay??contract.completedDay??contract.cancelledDay??'Indisponível'}</dd></div><div><dt>Duração</dt><dd>${contract.acceptedDay==null||contract.commercialEndedDay==null?'Indisponível':`${Math.max(0,contract.commercialEndedDay-contract.acceptedDay)} dias`}</dd></div><div><dt>Receita contratada</dt><dd>${money(contract.monthlyFee)}/mês</dd></div><div><dt>Receita recorrente realizada</dt><dd>${realized==null?'Indisponível · save anterior sem acumulador':money(realized)}</dd></div><div><dt>Implantação recebida</dt><dd>${manager.state.commercialHistoryPartial&&contract.totalSetupRevenue==null?'Indisponível':money(contract.totalSetupRevenue)}</dd></div><div><dt>Multas aplicadas</dt><dd>${manager.state.commercialHistoryPartial&&contract.totalPenalties==null?'Indisponível':money(contract.totalPenalties)}</dd></div><div><dt>Disponibilidade alcançada</dt><dd>${actual==null?'Indisponível':actual.toFixed(2)+'%'}</dd></div><div><dt>Estado final</dt><dd>${contract.status==='completed'?'Concluído':'Cancelado'}</dd></div><div><dt>Motivo</dt><dd>${esc(endReason)}</dd></div></dl></article>`;
  }).join('');
  return `<section class="cc-tab cc-history"><div class="cc-tab-heading"><div><span class="cc-eyebrow">REGISTRO COMERCIAL</span><h2>Histórico</h2></div><b>${ended.length} contratos encerrados</b></div><div class="cc-filters"><label>Estado<select data-history-state><option value="all" ${ui.historyState==='all'?'selected':''}>Todos</option><option value="completed" ${ui.historyState==='completed'?'selected':''}>Concluídos</option><option value="cancelled" ${ui.historyState==='cancelled'?'selected':''}>Cancelados</option></select></label><label>Modalidade<select data-history-type><option value="all" ${ui.historyType==='all'?'selected':''}>Todas</option><option value="cloud" ${ui.historyType==='cloud'?'selected':''}>Cloud</option><option value="colocation" ${ui.historyType==='colocation'?'selected':''}>Colocation</option></select></label><label>Buscar cliente<input type="search" data-history-search value="${esc(ui.historySearch)}" placeholder="Nome do cliente"></label></div>${manager.state.commercialHistoryPartial?'<p class="cc-partial">O salvamento não continha histórico detalhado anterior à migração. Esses valores aparecem como indisponíveis em vez de estimativas.</p>':''}<div class="cc-history-list">${rows||'<p class="cc-empty">Nenhum contrato encerrado corresponde aos filtros.</p>'}</div></section>`;
}
