import { TileRenderer } from './TileRenderer.js';import { HeatmapRenderer } from './HeatmapRenderer.js';import { AirflowRenderer } from './AirflowRenderer.js';import { EntityRenderer } from './EntityRenderer.js';
export class Renderer {
  constructor(canvas,camera,{tilePixels=14}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.camera=camera;this.tile=tilePixels;this.mode='normal';this.debug=false;this.hover=null;this.buildSystem=null;this.tileRenderer=new TileRenderer();this.heatmap=new HeatmapRenderer();this.airflow=new AirflowRenderer();this.entities=new EntityRenderer();}
  resize(){const dpr=Math.min(2,devicePixelRatio||1),r=this.canvas.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.dpr=dpr;}
  draw(world,simulation){this.resize();const ctx=this.ctx;ctx.setTransform(this.dpr,0,0,this.dpr,0,0);ctx.clearRect(0,0,this.canvas.width/this.dpr,this.canvas.height/this.dpr);ctx.fillStyle='#07111f';ctx.fillRect(0,0,this.canvas.width/this.dpr,this.canvas.height/this.dpr);ctx.save();ctx.scale(this.camera.zoom,this.camera.zoom);ctx.translate(-this.camera.x,-this.camera.y);this.tileRenderer.draw(ctx,world,this.tile);if(this.mode==='thermal')this.heatmap.draw(ctx,world,this.tile);if(this.mode==='airflow')this.airflow.draw(ctx,world,this.tile);this.entities.draw(ctx,world,this.tile,this.mode);if(this.mode==='fluid')this.drawFluidConnections(ctx,world);this.drawHover(ctx,world);if(this.debug)this.drawDebug(ctx,world);ctx.restore();this.drawLegend(ctx,simulation);}
  drawFluidConnections(ctx,world){const fluid=world.entities.filter(e=>['pipe','pump','tank','radiator','exchanger'].includes(e.type));ctx.strokeStyle='rgba(96,165,250,.55)';ctx.lineWidth=3;for(const a of fluid)for(const b of fluid){if(a.id>=b.id)continue;if(Math.abs(a.x-b.x)+Math.abs(a.y-b.y)!==1)continue;ctx.beginPath();ctx.moveTo((a.x+.5)*this.tile,(a.y+.5)*this.tile);ctx.lineTo((b.x+.5)*this.tile,(b.y+.5)*this.tile);ctx.stroke();}}
  drawHover(ctx,world){if(!this.hover||!world.inBounds(this.hover.x,this.hover.y))return;const {x,y}=this.hover;const valid=this.buildSystem?.selected?this.buildSystem.validator.canPlace(this.buildSystem.selected,x,y):true;ctx.strokeStyle=this.buildSystem?.selected?(valid?'#4ade80':'#f87171'):'#f8fafc';ctx.lineWidth=2/this.camera.zoom;ctx.strokeRect(x*this.tile+1,y*this.tile+1,this.tile-2,this.tile-2);if(this.buildSystem?.selected&&['fan','exhaust'].includes(this.buildSystem.selected)){const d=this.buildSystem.direction(),cx=(x+.5)*this.tile,cy=(y+.5)*this.tile;ctx.strokeStyle='#7dd3fc';ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+d.x*this.tile*3,cy+d.y*this.tile*3);ctx.stroke();}}
  drawDebug(ctx,world){if(!this.hover||!world.inBounds(this.hover.x,this.hover.y))return;const t=world.tileMap.get(this.hover.x,this.hover.y),txt=[`(${t.x},${t.y})`,t.material.name,`${t.temperature.toFixed(2)}°C`,`E ${(t.thermalEnergy/1000).toFixed(1)} kJ`,`air ${t.airflowX.toFixed(2)}, ${t.airflowY.toFixed(2)}`];ctx.font='10px monospace';const x=t.x*this.tile+this.tile+4,y=t.y*this.tile;ctx.fillStyle='rgba(2,6,23,.9)';ctx.fillRect(x,y,132,txt.length*13+8);ctx.fillStyle='#e2e8f0';txt.forEach((s,i)=>ctx.fillText(s,x+5,y+14+i*13));}
  drawLegend(ctx,sim){if(this.mode!=='thermal')return;const x=18,y=18,w=150,h=10,g=ctx.createLinearGradient(x,y,x+w,y);g.addColorStop(0,'rgb(20,80,220)');g.addColorStop(.5,'rgb(40,200,90)');g.addColorStop(.75,'rgb(245,180,40)');g.addColorStop(1,'rgb(230,35,35)');ctx.fillStyle='rgba(2,6,23,.8)';ctx.fillRect(x-8,y-9,w+16,38);ctx.fillStyle=g;ctx.fillRect(x,y,w,h);ctx.fillStyle='#e2e8f0';ctx.font='11px system-ui';ctx.fillText('10°C',x,y+25);ctx.fillText('80°C+',x+w-34,y+25);}
}
